<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\EQDeeps.Core\EQDeeps.Core.csproj" />
    <ProjectReference Include="..\..\tests\EQDeeps.TestSupport\EQDeeps.TestSupport.csproj" />
  </ItemGroup>
</Project>
